### ISSUE TITLE
Do you have the paper for cross-edge computation offloading? Tks

### ISSUE THREAD

**Issue by wuhuaming2006** [NarcissusHliangZhao/Implementation-of-MEC-papers#5]

**Comment by NarcissusHliangZhao** [comment]
Thanks for your interest in this repos. The code for cross-edge offloading is an algorithm proposed by me. The paper is under review now.

Cross-edge offloading is a new created repos now. Please find it in my profile page.

**Comment by wuhuaming2006** [comment]
Thanks so much! I'm very interested!
